immuni-app/immuni-backend-common

.github/PULL_REQUEST_TEMPLATE.md
This PR fixes the broken CONTRIBUTING link by pointing to the master branch file.
- Fixes #7
=> fix: broken CONTRIBUTING link in Pull Request template

immuni_common/models/marshmallow/validators.py, tests/test_helpers/test_marshmallow.py
Do not raise ValueErro if the list of Teks is empty. Simply return.
- Fixes #9
=> fix: allow empty list in TekListValidator

CONTRIBUTING.md, immuni_common/celery.py, immuni_common/core/config.py, immuni_common/helpers/logging.py, immuni_common/sanic.py, mypy.ini, tests/test_sanic.py
This PR implements a custom JSON formatter, which also redacts the output messages. Specifically, it obfuscates any IP and removes sensitive information form the logging `extra` fields.
It is used as part of the root logger, as well as for (i) Sanic, (ii) Gunicorn, and (iii) Celery.
- Fixes #12 
- Fixes #14
=> feat(logging): redacting JSON logging on Gunicorn and Celery

poetry.lock, pyproject.toml
Pinning dependencies makes the project more resilient against bugs introduced in newer versions of some packages.
Recently, an update of the package `kombu` caused the tests to be broken in CI.
=> fix: pinned dependencies

immuni_common/sanic.py
It's a good practice to avoid opening the swagger endpoints in production environments.
=> feat: do not include swagger blueprint in production

immuni_common/models/marshmallow/fields.py, immuni_common/models/marshmallow/schemas.py
Endpoint validation is now resilient to eventually inconsistent values returned by the Apple/Google Exposure notification SDK.
=> Resilience to eventual SDK inconsistencies

immuni_common/models/mongoengine/temporary_exposure_key.py
This PR adds the expires_at property to the TemporaryExposureKey model. This is useful to ensure we're not adding active TEKs during the ingestion processing of new batches.
=> feat: add expires_at to TemporaryExposureKey model

immuni_common/helpers/logging.py, poetry.lock, pyproject.toml
Due to wrong propagation directives, Sanic and Uvicorn logging handlers were propagating to the root logger too.
This PR removes duplicate logs. Specifically:
- It explicitly sets `propagate=False` for Sanic.
- It bumps Uvicorn's version, which contains [a fix](https://github.com/encode/uvicorn/pull/623) to this behaviour.
=> fix(logging): remove duplicate logs

immuni_common/celery.py
Both _immuni-backend-exposure-ingestion_ and _immuni-backend-analytics_ would use a utility to convert a crontab string to a crontab object.
The method is then moved to common.
=> feat(celery): add common string to crontab utility

immuni_common/models/marshmallow/fields.py, immuni_common/models/marshmallow/validators.py, tests/test_helpers/test_marshmallow.py
Add a min and max length check to the base64 marshmallow validator.
=> feat: add min and max length to base64 validator

mypy.ini
Ignore missing imports from `certvalidator`.
=> feat(mypy): add certvalidator to ignored missing imports

immuni_common/core/config.py, immuni_common/helpers/sanic.py, immuni_common/helpers/utils.py, pyproject.toml, tests/test_helpers/test_dummy_requests.py
This PR adds the 'handle_dummy_requests' decorator, which is capable of handling all dummy requests across the different microservices.
=> feat: add handle_dummy_requests decorator

immuni_common/celery.py, immuni_common/core/config.py, immuni_common/monitoring/core.py
This PR exposes an HTTP server on the specified CELERY_PROMETHEUS_PORT.
Before this, the metrics were populated, yet unquerable from the outside.
=> feat(monitoring): expose metrics from a celery context

immuni_common/celery.py
This PR silences an exception thrown when starting the monitoring server after configuring Celery.
=> fix(celery): silence monitoring safe exception

poetry.lock, pyproject.toml
There is a "hidden" dependency on `dnspython` (from mongoengine, through pymongo) that should have been pinned to version < 2, but it has not (or at least, it hasn't been done correctly).
Unfortunately, dnspython 2.0.0, released about 10 days ago, seems to introduce breaking changes (no changelog?), so if you update your lockfile in any way, you'll end up with a DNS failure.
For now, we then pin dnspython as a precaution.
=> fix(poetry): pin dnspython to prevent DNS failure

immuni_common/sanic.py
Prevent caching on `/` and `/metrics` endpoints.
- Fixes #29
=> feat(sanic): prevent caching of status and metrics endpoints

immuni_common/models/marshmallow/fields.py
At least in iOS 13.7 the list can be of 4 elements. This PR relaxes the strict check of only 3 elements being allowed, allowing 4 as well.
=> fix: allow attenuation duration list with length 4

immuni_common/sanic.py
Have the endpoint methods async, so as to properly use the cache decorator for cache-control headers injection.
=> fix(sanic): make the metrics endpoint async

dev/pyproject.toml, pyproject.toml
In the past days, poetry started showing `ModuleNotFoundError: No module named 'setuptools'` when installing common from one of the microservices projects.
We also tried to upgrade poetry to the latest 1.1.0, but without improvements (different error, though).
In the future, we will evaluate again this "workaround".
=> fix(poetry): add required dependency

immuni_common/uvicorn.py, mypy.ini
Custom worker setting lifespan=on to fail over exceptions raised within the worker startup.
For instance, without this, an exception triggered during the managers initialization is never caught.
NOTE: This lifespan option cannot be passed through the command line of gunicorn since the latter does not support it.
=> feat(api): custom uvicorn worker

immuni_common/core/config.py
Move a configuration used by both analytics and settings microservices.
As a follow-up, the two services will remove their own config in favour of using this one.
=> feat: move config to common to later use it in two microservices

mypy.ini
Not having this configuration prevents mypy from running properly in the different microservices.
=> fix: add mypy_path for common to support poetry upgrade

immuni_common/models/enums.py, tests/test_models/test_batch_file.py, tests/test_models/test_batch_file_eu.py
In this PR, we align the transmission risk levels to the one recommended by [the official Apple documentation](https://developer.apple.com/documentation/exposurenotification/enexposureinfo/3583716-transmissionrisklevel#discussion).
Given the current equal weight being given to every single option, nothing should change GAEN-wise.
For this reason, we at least try to align with the one semantically closer to what we intend doing code-wise, aka setting it to the highest risk level in immuni-exposure-ingestion.
=> fix(trl): adapt to latest documentation
